export const EMIT_FINISH_FIRST_LAUNCH_APP = 'EMIT_FINISH_FIRST_LAUNCH_APP';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const UPDATE_COMMON_STATE = 'UPDATE_COMMON_STATE';
export const APP_DID_MOUNT = 'APP_DID_MOUNT';
export const UPDATE_LOADING_SCREEN = 'UPDATE_LOADING_SCREEN';
export const SHOW_LOADING_SCREEN = 'SHOW_LOADING_SCREEN';
export const HIDE_LOADING_SCREEN = 'HIDE_LOADING_SCREEN';

export const REGISTER = 'REGISTER';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
